[env:m5stack_paper]
platform = espressif32
board = m5stack_paper
framework = arduino
monitor_speed = 115200
board_build.partitions = default_16MB.csv
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D BOARD_HAS_PSRAM
    -D APP_VERSION=\"3.0.0\"
    -D BUILD_TAG=\"Weather\ Monitor\"

    -mfix-esp32-psram-cache-issue
    -Wno-deprecated-declarations

lib_deps =
    m5stack/M5Unified@^0.1.17
    mathieucarbou/ESPAsyncWebServer @ ^3.6.0
    bblanchon/ArduinoJson @ ^7.3.0
    ricmoo/QRCode @ ^0.0.1
